---
####ADICIONAR DISCO NUEVO SO EN VMWARE#####
# Elaborado por: SID - Implementacion     #                              
# Fecha: 09 Julio de 2021                 #
# Compañía: CWC                           #  
# Plataforma: VMWARE                      #
###########################################
# Este playbook agrega un VM-Disk a las   #
# VM desplegadas o existentes             #   
###########################################
- hosts: all
  vars:
  - ansible_python_interpreter: /usr/bin/python3          
  tasks:
  - name: Create a snapshot                             
    vmware_guest_disk:                                    # Modulo para despliegue
        hostname: "{{ VCENTER }}"                         # IP del vCenter
        username: "{{ USER_VCENTER }}"                    # Usuario de vCenter
        password: "{{ CONTRASEÑA }}"                      # Password de vCenter
        validate_certs: False                             
        datacenter: "{{ DATACENTER }}"                    # Nombre del Datacenter donde se va a desplegar
        name: "{{ Servidor }}"                            # Nombre de servidor a cual hay q Asignar el disco
        disk:
          - size_gb: "{{ Tamaño }}"                       # Tamaño de Disco    
            type: thin                                    # Formato de disco
            state: present                       
            scsi_controller: '0'                          # Scsi donde se va a utilizarr      
            unit_number: "{{ slot }}"                     # Numero de Slot donde va ser asiganado 
            scsi_type: 'paravirtual'                      # Tipo de Disco 
            datastore: "{{ DS }}"                        # Data estorage dodne va quedar el disco
...            
