---
########CREACION PORTGROUP EN VMWARE#######
# Elaborado por: SID - Implementacion     #                              
# Fecha: 09 Julio de 2021                 #
# Compañía: WCW                           #  
# Plataforma: VMWARE                      #
###########################################
- hosts: all
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Add Portgroup with Promiscuous
      vmware_portgroup:
        hostname: "{{ VCENTER }}"                     # IP del vCenter
        username: "{{ USER_VCENTER }}"                # Usuario de vCenter
        password: "{{ CONTRASEÑA }}"                  # Password de vCenter
        esxi_hostname: "{{ ESXI_HOSTNAME }}"          # IP del esx
        switch_name: "{{ vswitch_name }}"             # Nombre Vswicht donde va quedar el Portgroup
        portgroup_name: "{{ portgroup_name }}"        # Nombre de PortGroup a visualizar en vmware
        vlan_id: "{{ vlan_id }}"                      # Nmbre o  numero  de la Vlan a crear
        validate_certs: False
      delegate_to: localhost
