---
#########Copia Archivo Evidencias#########
# Elaborado por: SID - Implementacion    #                              
# Fecha: 09 Julio de 2021                #
# Compañía: WCW                          #  
# Plataforma: LINUX                      #
##########################################
- hosts: all
  tasks:
    - name: Copia FTP
      shell: sftp -i /etc/ansible/ftp_evidencias  evidencias@s-2691eeed50aa4b6db.server.transfer.us-east-1.amazonaws.com
