---
########CREACION PORTGROUP EN VMWARE#######
# Elaborado por: SID - Implementacion     #                              
# Fecha: 09 Julio de 2021                 #
# Compañía: WCW                           #  
# Plataforma: VMWARE                      #
###########################################
- hosts: all
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Add Portgroup with Promiscuous
      vmware_portgroup:
        hostname: "10.215.99.55"                      # IP del vCenter
        username: "administrator@vsphere.local"       # Usuario de vCenter
        password: "Lab2021*"                          # Password de vCenter
        esxi_hostname: '10.215.99.60'                 # IP del esx
        switch_name: "{{ vswitch_name }}"             # Nombre Vswicht donde va quedar el Portgroup
        portgroup_name: "{{ portgroup_name }}"        # Nombre de PortGroup a visualizar en vmware
        vlan_id: "{{ vlan_id }}"                      # Nmbre o  numero  de la Vlan a crear
        validate_certs: False
      delegate_to: 10.215.99.103
