---
####### CREACION USUARIO SO WINDOWS #######
# Elaborado por: SID - Implementacion     #                              
# Fecha: 09 Julio de 2021                 #
# Compañía: WCW                           #  
# Plataforma: LINUX                       #
###########################################
- name: Add a user
  hosts: all
  gather_facts: false
  tasks:
    - name: Add User
      win_user:
        name: "{{ USER_NAME }}"
        password: "{{ PASSWORD }}"
        state: present
...
