---
####ADICIONAR DISCO NUEVO SO EN VMWARE#####
# Elaborado por: SID - Implementacion     #                              
# Fecha: 09 Julio de 2021                 #
# Compañía: WCW                           #  
# Plataforma: LINUX                       #
###########################################
- hosts: all
  vars:
  - ansible_python_interpreter: /usr/bin/python3 
  tasks:
  - name: Create a snapshot
    vmware_guest_disk:
        hostname: '10.215.99.55'                                         
        username: 'administrator@vsphere.local'
        password: 'Lab2021*'
        validate_certs: False
        datacenter: 'CURANSIBLEDCLAB01'
        name: "{{ Servidor }}"
        disk:
          - size_gb: "{{ Tamaño }}"
            type: thin
            state: present
            scsi_controller: '0'
            unit_number: "{{ slot }}"
            scsi_type: 'paravirtual'
            datastore: 'Management'
