---
####ADICIONAR DISCO NUEVO SO EN VMWARE#####
# Elaborado por: SID - Implementacion     #                              
# Fecha: 09 Julio de 2021                 #
# Compañía: WCW                           #  
# Plataforma: VMWARE                      #
###########################################
- hosts: all
  vars:
  - ansible_python_interpreter: /usr/bin/python3          
  tasks:
  - name: Create a snapshot                             
    vmware_guest_disk:                                    # Modulo para despliegue
        hostname: '10.215.99.55'                          # IP del vCenter                
        username: 'administrator@vsphere.local'           # Usuario de vCenter
        password: 'Lab2021*'                              # Password de vCenter   
        validate_certs: False                             
        datacenter: 'CURANSIBLEDCLAB01'                   # Cluster Vmware
        name: "{{ Servidor }}"                            # Nombre de servidor a cual hay q Asignar el disco
        disk:
          - size_gb: "{{ Tamaño }}"                       # Tamaño de Disco    
            type: thin                                    # Modo de disco
            state: present                       
            scsi_controller: '0'                          # Scsi donde se va a utilizarr      
            unit_number: "{{ slot }}"                     # Numero de Slot donde va ser asiganado 
            scsi_type: 'paravirtual'                      # Tipo de Disco 
            datastore: 'Management'                       # Data estorage dodne va quedar el disco
