---
####### EJECUCION EVIDENCIA WINDOWS #######
# Elaborado por: SID - Implementacion     #                              
# Fecha: 09 Julio de 2021                 #
# Compañía: WCW                           #  
# Plataforma: Windows                     #
###########################################
- hosts: all
  tasks:
  - name: Ejecutar Script en PowerShell
    win_command: powershell.exe -ExecutionPolicy ByPass -File C:\admin\evidencias1.ps1   # Ejecuta un  PS1 
    register: result
  - debug: var=result.stdout_lines 
  
  - name: hostname
    win_command: cmd.exe /c hostname > C:\tools\config\VM.txt                            # Crea nombre de la maquina
    register: hostname
    
###copair Archivo filsercerver#####    
    
  - name: Copy File
    win_copy:
      src: C:\tools\config\VM.txt
      dest: C:\admin\VM.txt
      remote_src: yes
