---
######TOMA EVIDENCIAS SERVIDORES LINUX######
# Elaborado por: SID - Implementacion      #                              
# Fecha: 09 Julio de 2021                  #
# Compañía: WCW                            #  
# Plataforma: LINUX                        #
############################################
- name: evidencia
  hosts: all
  tasks:
    - name: nombre servidor - hostname                                   
      shell: hostname > /tmp/Evidencias.txt                           # Crea archivo Evidencias.txt 
      shell: echo -e "\n###HOSTNAME###" >> /tmp/Evidencias.txt        # Agrega Liniea al Archivo         
      register: out
    - debug: var=out.stdout_lines
    
    - name: nombre servidor - hostname1                                                   
      shell: hostname >> /tmp/Evidencias.txt                          # Agrega el Hostname a la archivo        
      register: out
    - debug: var=out.stdout_lines
    
    - name: uname
      shell: echo -e "\n###UNAMEA###" >> /tmp/Evidencias.txt          # Agrega linea ###UNAMEA###   
      register: out
    - debug: var=out.stdout_lines

    - name: version y hostname - uname -a                             
      shell: uname -a >> /tmp/Evidencias.txt                          # Agrega uname -a  al archivo 
      register: out
    - debug: var=out.stdout_lines

    - name: discos df -h-
      shell: echo -e "\n###DISCOSDF###" >> /tmp/Evidencias.txt        # Agrega linea ###DISCOSDF###  
      register: out
    - debug: var=out.stdout_lines
    
    - name: discos df -h
      shell: df -h >> /tmp/Evidencias.txt                             # Agrega df -h al archivo
      register: out
    - debug: var=out.stdout_lines
    
    - name: discosLSBLK
      shell: echo -e "\n###DISCOSLSBLK###" >> /tmp/Evidencias.txt     # Agrega linea ###DISCOSLSBLK###
      register: out
    - debug: var=out.stdout_lines
    
    - name: discos -Total - lsblk |grep disk                          # Agrega lsblk |grep disk al archivo 
      shell: lsblk >> /tmp/Evidencias.txt
      register: out
    - debug: var=out.stdout_lines
    
    - name: Procesadors nproc1
      shell: echo -e "\n###PROCESADORES###" >> /tmp/Evidencias.txt   # Agrega ###PROCESADORES### al archivo
      register: out
    - debug: var=out.stdout_lines
    
    - name: Procesadors nproc
      shell: nproc >> /tmp/Evidencias.txt                            # Agrega line nproc al archivo    
      register: out
    - debug: var=out.stdout_lines
    
    - name: mEMORIA
      shell: echo -e "\n###MEMORIASWAP###" >> /tmp/Evidencias.txt    # Agrega ###MEMORIASWAP### al archivo 
      register: out
    - debug: var=out.stdout_lines
       
    - name: memory - vmstat >>
      shell: vmstat >> /tmp/Evidencias.txt                            # Agrega line vmstat al archivo      
      register: out
    - debug: var=out.stdout_lines
    
    - name: memory - free -m 
      shell: free -m >> /tmp/Evidencias.txt                           # Agrega line free -m  al archivo   
      register: out
    - debug: var=out.stdout_lines
    
    - name: memory - swapon -s 
      shell: swapon -s >> /tmp/Evidencias.txt                         # Agrega line swapon -s al archivo    
      register: out
    - debug: var=out.stdout_lines
    
    - name: UPTIME
      shell: echo -e "\n###UPTIME###" >> /tmp/Evidencias.txt          # Agrega linea ###UPTIME###
      register: out
    - debug: var=out.stdout_lines
    
    - name: Uptime - uptime
      shell: uptime >> /tmp/Evidencias.txt                            # Agrega line uptime al archivo 
      register: out
    - debug: var=out.stdout_lines
    
    - name: timedatectl
      shell: echo -e "\n###DATE###" >> /tmp/Evidencias.txt            # Agrega linea ###DATE###
      register: out
    - debug: var=out.stdout_lines

    - name: date - timedatectl
      shell: timedatectl >> /tmp/Evidencias.txt                       # Agrega resultado timedatectl al archivo 
      register: out 
    - debug: var=out.stdout_lines    
   
    - name: systemctl
      shell: echo -e "\n###SERVICES###" >> /tmp/Evidencias.txt        # Agrega linea ###SERVICES###          
      register: out
    - debug: var=out.stdout_lines
    
    - name: Servicio ejecutado - systemctl | grep running
      shell: systemctl | grep running >> /tmp/Evidencias.txt          # Agrega resultado systemctl | grep running al archivo 
      register: out
    - debug: var=out.stdout_lines
    
    - name: yum history 
      shell: echo -e "\n###YUMHISTORY###" >> /tmp/Evidencias.txt      # Agrega linea n###YUMHISTORY###
      register: out
    - debug: var=out.stdout_lines
                    
    - name: Ultimas actulizaciones - yum history                      # Agrega resultado yum history al archivo                  
      shell: yum history >> /tmp/Evidencias.txt
      register: out
    - debug: var=out.stdout_lines
    
    - name: Messages_Log 
      shell: echo -e "\n###LOGMESSENGER###" >> /tmp/Evidencias.txt    # Agrega linea ###LOGMESSENGER### 
      register: out
    - debug: var=out.stdout_lines
    
    - name: Messages
      shell: tail --lines=10 /var/log/messages >> /tmp/Evidencias.txt # Agrega resultado tail --lines=10 al archivo   
      register: out
    - debug: var=out.stdout_lines
    
    #- name: Susbsicripcion - subscription-manager list               # Agrega resultado de la info de la subscripcion 
     # shell: subscription-manager list
      #register: out
    #- debug: var=out.stdout_lines 
...
