---
#### INSTALAR PAQUETES CHOCOLATEY WINDOWS##
# Elaborado por: SID - Implementacion     #                              
# Fecha: 09 Julio de 2021                 #
# Compañía: WCW                           #  
# Plataforma: WINDOWS                     #
###########################################
# Este playbook utiliza un repositorio de #
# https://chocolatey.org/ para instalcion #
# en Plataforma Windows                   #
###########################################
- hosts: all  
  gather_facts: false
  tasks:
    - name: Install Chocolatey packages
      win_chocolatey:                     # Conectarse al Modulo chocolatey
        name:
        - slack                           # Instalacion Paquete SLACK
        - dropbox                         # Instalacion Paquete DROPBOX    
        - google-chrome-x64               # Instalacion Paquete CHROME  
        - 7zip                            # Instalacion Paquete 7ZIP
        state: latest
