---
#### INSTALAR PAQUETES CHOCOLATEY WINDOWS##
# Elaborado por: SID - Implementacion     #                              
# Fecha: 09 Julio de 2021                 #
# Compañía: WCW                           #  
# Plataforma: LINUX                       #
###########################################
- hosts: all  
  gather_facts: false
  tasks:
    - name: Install Chocolatey packages
      win_chocolatey:
        name:
        - slack
        - dropbox
        - google-chrome-x64
        - 7zip
        state: latest
