---
- hosts: all  
  gather_facts: false
  tasks:
    - name: Install Chocolatey packages
      win_chocolatey:
        name:
        - slack
        - dropbox
        - google-chrome-x64
        - 7zip
        state: latest
