---
- hosts: all
  connection: local
  var:
    hostname: 10.215.99.55
    username: administrator@vsphere.local
    password: Lab2021*
    datacenter: CURANSIBLEDCLAB01
    folder: "/VMs-Windows/"
    name: Windows1
  collections: community.vmware_guest_snapshot 
  tasks:
    - name: Create a snapshot
      vmware_guest_snapshot:
           hostname: "{{ vcenter_hostname }}"
           username: "{{ vcenter_username }}"
           password: "{{ vcenter_password }}"
           datacenter: "{{ datacenter_name }}"
           folder: "/{{ datacenter_name }}/vm/"
           name: "{{ guest_name }}"
           state: present
           snapshot_name: snap1
           description: snap1_description
       delegate_to: localhost
 
    - name: Remove a snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        folder: "/{{ datacenter_name }}/vm/"
        name: "{{ guest_name }}"
        state: absent
        snapshot_name: snap1
      delegate_to: localhost
