---
- hosts: all
  connection: local
  tasks:
  - name: snpa
    vmware_guest_snapshot: 
      hostname: 10.215.99.55
      username: administrator@vsphere.local
      password: Lab2021*
      validate_certs: False
      datacenter: CURANSIBLEDCLAB01
      folder: /VMs-Windows/
      name: "{{ item }}"
      state: present
      snapshot_name: "{{ SNAP }}"
      description: snap1_description
    delegate_to: localhost

tasks:
  - name: Ejecutar Script en PowerShell
    hell: /usr/bin/pwsh /etc/ansible/snapshot.ps1
    register: result
  - debug: var=result.stdout_lines  
...
