---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
   - name: Add a user linux
     user:
       name: AWX
       password: "{{ 'Colombia2021*' | password_hash('sha512') }}"
       shell: /bin/bash
...
