- name: Create new VM - {{ vm_name }}
  vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vm_datacenter }}"
      cluster: "{{ vm_cluster }}"
      validate_certs: no
      folder: "{{ vm_folder }}"
      name: "{{ vm_name }}" 
      state: poweredoff
      guest_id: rhel7_64Guest
      datastore: "{{ vm_datastore }}"
      disk:
        - size_gb: 10
      hardware:
          memory_mb: "{{ vm_mem }}"
          memory_reservation: "{{ (vm_mem / 2) | int }}"
          num_cpus: "{{ vm_cpu }}"
          cpu_reservation: "{{ (vm_cpu * 256) | int }}"
          scsi: paravirtual
          boot_firmware: efi
      networks:
        - name: "{{ vm_network }}"
          device_type: vmxnet3
      customvalues:
        - key: "RemoteDisplay.maxConnections"
	  value: "3"
	- key: "isolation.tools.copy.disable"
          value: "False"
        - key: "isolation.tools.paste.disable"
          value: "False"
        - key: "isolation.tools.diskShrink.disable"
          value: "False"
        - key: "isolation.tools.diskWiper.disable"
          value: "False"
        - key: "tools.setInfo.sizeLimit"
          value: "1048576"
        - key: "RemoteDisplay.vnc.enabled"
          value: "False"
        - key: "tools.guestlib.enableHostInfo"
          value: "False"
	- key: "isolation.tools.dnd.disable" 
	  value: "True"
	- key: "isolation.tools.setGUIOptions.enable"
	  value: "True"
        - key: "isolation.device.connectable.disable"
          value: "True"	
	- key: "isolation.device.edit.disable"
	  value: "True"
	- key: "vmci0.unrestricted"
	  value: "False"
	- key: "log.rotateSize"
	  value: "1000000"
	- key: "log.keepOld"
	  value: "10"
	- key: "guest.command.enabled"
	  value: "False"
	- key: "tools.guestlib.enableHostInfo"
	  value: "False"
	- key: "vcpu.hotadd"
	  value: "True"
	- key: "mem.hotadd"
	  value: "True"
	- key: "devices.hotplug"
	  value: "False"
	- key: "snapshot.redoNotWithParent"
	  value: "true"
      wait_for_ip_address: no
  register: vm_deploy
