---
- hosts: all
  tasks:
  - name: Create registry path MyCompany
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
      name: WUServer
      data: https://colwsus.cbs-cloud.com:8531
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate
      name: WUStatusServer
      data: https://colwsus.cbs-cloud.com:8531
